### ISSUE TITLE
startRecording() called on an uninitialized AudioRecord

### ISSUE THREAD

**Issue by ivanove** [adrielcafe/AndroidAudioRecorder#10]
I had this error when I try to record Audio, I looked for a solution but what I found is that Marshmallow version of Android has a bug according to this line : 

> getSlotFromBufferLocked: unknown buffer: 0xb8b24798

```
 java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                              at android.media.AudioRecord.startRecording(AudioRecord.java:895)
                                                                              at omrecorder.PullTransport$AbstractPullTransport.preparedSourceToBePulled(PullTransport.java:89)
                                                                              at omrecorder.PullTransport$AbstractPullTransport.start(PullTransport.java:70)
                                                                              at omrecorder.AbstractRecorder$1.run(AbstractRecorder.java:29)
                                                                              at java.lang.Thread.run(Thread.java:818)
09-18 11:42:25.921 29302-29328/com.surtymar.application E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb8b24798
```

Hope someone will help me.

**Comment by adrielcafe** [comment]
Hi @ivanove,
Could you check if the permission below is allowed? ([like this](http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/))
`<uses-permission android:name="android.permission.RECORD_AUDIO"/>`

**Comment by ivanove** [comment]
Yes, the problem was juste in MarshMallow's version, adding permission in run time solve the issue.
I'll close it.
Thank's
