### ISSUE TITLE
Can not be used in android7.0

### ISSUE THREAD

**Issue by jcj27757** [adrielcafe/AndroidAudioRecorder#26]
in android7.0  invalid generated file。

**Comment by laylizzlle** [comment]
Have you found a way around it because it's not working here too.

**Comment by nomi2013** [comment]
@jcj27757  have you got any working solution on Android 7.0(Not working this Audio Recorder).

**Comment by Slobodan988** [comment]
You ned to add those permissions in manifest.xml file:

<uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />

**Comment by joreilly** [comment]
Just to confirm that I'm using this without any problem on Android 7.0

**Comment by firebaseempower** [comment]
not working for me in android 7.1.2

**Comment by UniverQuie** [comment]
I got a problem on Android 7.0 
08-07 16:00:14.657 22667-22667/cafe.adriel.androidaudiorecorder.example E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
08-07 16:00:14.657 22667-22667/cafe.adriel.androidaudiorecorder.example E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
08-07 16:00:14.658 22667-22667/cafe.adriel.androidaudiorecorder.example E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
08-07 16:00:14.658 22667-22667/cafe.adriel.androidaudiorecorder.example E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
08-07 16:00:14.729 22667-22681/cafe.adriel.androidaudiorecorder.example E/MediaPlayer: error (1, -2147483648)
08-07 16:00:14.730 22667-22667/cafe.adriel.androidaudiorecorder.example W/System.err: java.io.IOException: Prepare failed.: status=0x1
	at android.media.MediaPlayer._prepare(Native Method)
	at android.media.MediaPlayer.prepare(MediaPlayer.java:1188)
	at cafe.adriel.androidaudiorecorder.AudioRecorderActivity.startPlaying(AudioRecorderActivity.java:380)
08-07 16:00:14.731 22667-22667/cafe.adriel.androidaudiorecorder.example W/System.err:     at cafe.adriel.androidaudiorecorder.AudioRecorderActivity.access$500(AudioRecorderActivity.java:38)
	at cafe.adriel.androidaudiorecorder.AudioRecorderActivity$3.run(AudioRecorderActivity.java:278)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6396)
	at java.lang.reflect.Method.invoke(Native Method)
08-07 16:00:14.732 22667-22667/cafe.adriel.androidaudiorecorder.example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
