### ISSUE TITLE
crash on android 4.4.2

### ISSUE THREAD

**Issue by Wilshion** [adrielcafe/AndroidAudioRecorder#41]
E/AndroidRuntime(24736): java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
E/AndroidRuntime(24736): 	at android.media.AudioRecord.startRecording(AudioRecord.java:554)
E/AndroidRuntime(24736): 	at omrecorder.PullTransport$AbstractPullTransport.preparedSourceToBePulled(PullTransport.java:89)
E/AndroidRuntime(24736): 	at omrecorder.PullTransport$AbstractPullTransport.start(PullTransport.java:70)
E/AndroidRuntime(24736): 	at omrecorder.AbstractRecorder$1.run(AbstractRecorder.java:29)
E/AndroidRuntime(24736): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager( 1354):   Force finishing activity com.xxx.ksrivertreat/cafe.adriel.androidaudiorecorder.AudioRecorderActivity

**Comment by AlexSheiko** [comment]
I have the same issue on Android 4.4 emulator
