### ISSUE TITLE
Can not work in android 8

### ISSUE THREAD

**Issue by lbx2015** [adrielcafe/AndroidAudioRecorder#68]
java.lang.RuntimeException: could not build OutputStream from this filerecorded_audio.wav
        at omrecorder.AbstractRecorder.outputStream(AbstractRecorder.java:44)
        at omrecorder.AbstractRecorder.<init>(AbstractRecorder.java:22)
        at omrecorder.Wav.<init>(Wav.java:35)
        at omrecorder.OmRecorder.wav(OmRecorder.java:36)
        at cafe.adriel.androidaudiorecorder.AudioRecorderActivity.resumeRecording(AudioRecorderActivity.java:282)
        at cafe.adriel.androidaudiorecorder.AudioRecorderActivity.access$200(AudioRecorderActivity.java:33)
        at cafe.adriel.androidaudiorecorder.AudioRecorderActivity$1.run(AudioRecorderActivity.java:223)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6589)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/recorded_audio.wav (Is a directory)

**Comment by aliraza96** [comment]
Have you solved this problem yet? Please reply

**Comment by zhubinsheng** [comment]
(Is a directory)？？ what happened
